databases:
  - name: PaymentsIQ_production
    databaseName: PaymentsIQ_production
    user: natanim

services:
  - type: web
    name: PaymentsIQ
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: PaymentsIQ_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
